name: Setup Node
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Get secrets by name - infra
      uses: aws-actions/aws-secretsmanager-get-secrets@v1
      with:
        secret-ids: |
          SECRET_INFRA,infra-${{ inputs.environment }}-common/values
        parse-json-secrets: true

    - name: make envfile
      uses: SpicyPizza/create-envfile@v1.3
      with:
        envkey_NODE_ENV: ${{ inputs.environment }}
        envkey_AWS_IDENTIFIER: ${{ env.SECRET_INFRA_AWS_IDENTIFIER }}
        envkey_AWS_SUBNET_ID1: ${{ env.SECRET_INFRA_AWS_SUBNET_ID1 }}
        envkey_AWS_SUBNET_ID2: ${{ env.SECRET_INFRA_AWS_SUBNET_ID2 }}
        envkey_AWS_LAMBDA_SECURITY_GROUP_ID: ${{ env.SECRET_INFRA_LAMBDA_SECURITY_GROUP_ID }}
        envkey_AWS_S3_STORAGE_ID: ${{ env.SECRET_INFRA_S3_STORAGE_ID_CORE }}
        envkey_AWS_WAF_NAME: ${{ env.SECRET_INFRA_AWS_WAF_NAME }}
        envkey_AWS_CLOUDFRONT_WAF_NAME: ${{ env.SECRET_INFRA_AWS_CLOUDFRONT_WAF_NAME }}

    - name: make config.json
      run: aws s3 cp s3://${{ env.SECRET_INFRA_S3_STORAGE_ID_MAIN }}/app/core/config.json ./config.json
      shell: bash

    - name: npm ci
      run: npm ci
      shell: bash

inputs:
  environment:
    description: 'The environment'
    required: true
    default: 'develop'
  aws_region:
    description: 'The AWS region to use'
    required: true
    default: 'ap-northeast-1'
  aws_access_key_id:
    description: 'aws access key id'
    required: true
  aws_secret_access_key:
    description: 'aws secret access key'
    required: true
