STAGE: ${sls:stage, 'offline'}
TZ: Asia/Tokyo
AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000 --openssl-legacy-provider'
NODE_ENV: production
REGION: ${self:provider.region}
AWS_IDENTIFIER: ${param:AWS_IDENTIFIER, ''}
AWS_S3_STORAGE_ID: ${param:AWS_S3_STORAGE_ID}
