STAGE: ${sls:stage, 'offline'}
TZ: Asia/Tokyo
AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000 --openssl-legacy-provider'
NODE_ENV: production
REGION: ${self:provider.region}
GCP_SA_KEY: ${param:GCP_SA_KEY}
SLACK_BOT_OAUTH_TOKEN: ${param:SLACK_BOT_OAUTH_TOKEN}
SLACK_BOT_POST_CHANNEL: ${param:SLACK_BOT_POST_CHANNEL}
AWS_S3_STORAGE_ID: ${param:AWS_S3_STORAGE_ID}
