- Effect: Allow
  Action:
    - logs:CreateLogGroup
    - logs:CreateLogStream
    - logs:PutLogEvents
  Resource: 
    - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${self:service}-${self:provider.stage}-*"
- Effect: "Allow"
  Action:
    - "s3:GetObject"
    - "s3:PutObject"
  Resource:
    - "arn:aws:s3:::${param:AWS_S3_STORAGE_ID}/*"
    - "arn:aws:s3:::${param:AWS_S3_STORAGE_ID}/*"
- Effect: "Allow"
  Action:
    - "s3:ListBucket"
  Resource:
    - "*"
