default:
  SETTING_LOG_FULL_EXECUTION_DATA: true
  AWS_IDENTIFIER: ${env:AWS_IDENTIFIER, ''}
  AWS_SUBNET_ID1: ${env:AWS_SUBNET_ID1, ''}
  AWS_SUBNET_ID2: ${env:AWS_SUBNET_ID2, ''}
  AWS_LAMBDA_SECURITY_GROUP_ID: ${env:AWS_LAMBDA_SECURITY_GROUP_ID, ''}
  AWS_S3_STORAGE_ID: ${env:AWS_S3_STORAGE_ID, ''}
  AWS_WAF_NAME: ${env:AWS_WAF_NAME, ''}
  AWS_CLOUDFRONT_WAF_NAME: ${env:AWS_CLOUDFRONT_WAF_NAME, ''}

offline:
  API_DOMAIN: localhost
  DOMAIN_NAME: example.com
  SETTING_LOG_RETENTION_IN_DAYS: 14
  SETTING_LOG_LEVEL: ALL
  CRON_BATCH_MAIN: cron(10 * ? * * *)

develop:
  API_DOMAIN: example.com
  DOMAIN_NAME: example.com
  SETTING_LOG_RETENTION_IN_DAYS: 30
  SETTING_LOG_LEVEL: ALL
  CRON_BATCH_MAIN: cron(0 0 ? * MON-FRI *) # every MON-FRI 1 days, 09:00 JST

production:
  API_DOMAIN: example.com
  DOMAIN_NAME: example.com
  SETTING_LOG_RETENTION_IN_DAYS: 400
  SETTING_LOG_LEVEL: ALL
  CRON_BATCH_MAIN: cron(0 0 * * ? *) # every 1 days - 09:00 JST
